# Generated by Django 4.2.23 on 2025-08-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rating_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movieId',
            new_name='movie',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('userId', 'movie')},
        ),
    ]
