# Generated by Django 4.2.23 on 2025-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_movieid_rating_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
