# Generated by Django 4.2.23 on 2025-08-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_populate_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_rating',
        ),
    ]
