# Generated by Django 4.2.23 on 2025-08-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_person_tag_movie_imdb_id_movie_overview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecast',
            options={'ordering': ['order', 'id']},
        ),
    ]
