# Generated by Django 4.2.23 on 2025-08-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_moviecast_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movietag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='movietag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
