# Generated by Django 4.2.23 on 2025-08-14 17:50


from django.db import migrations
from django.utils.text import slugify

def backfill(apps, schema_editor):
    Movie = apps.get_model("api", "Movie")
    for m in Movie.objects.all():
        if not getattr(m, "slug", None):
            base = slugify(f"{m.title}-{m.year or ''}") or "movie"
            m.slug = f"{base}-{m.movieId}"
            m.save(update_fields=["slug"])

class Migration(migrations.Migration):
    dependencies = [("api", "0011_genre_alter_moviecast_unique_together_and_more")]
    operations = [migrations.RunPython(backfill, migrations.RunPython.noop)]




