# Generated by Django 4.2.23 on 2025-08-14 19:17

from django.db import migrations, models
def backfill_for_not_null(apps, schema_editor):
    Movie = apps.get_model("api", "Movie")
    # overview: replace NULL with empty string
    Movie.objects.filter(overview__isnull=True).update(overview="")

    # rating fields: replace NULLs with defaults
    Movie.objects.filter(average_rating__isnull=True).update(average_rating=0.0)
    Movie.objects.filter(rating_count__isnull=True).update(rating_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_backfill_overview_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
