# Generated by Django 4.2.23 on 2025-08-14 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_list_review_listitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(db_index=True, unique=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(default='v1', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('movie', 'movie'), ('user', 'user'), ('tag', 'tag')], max_length=8)),
                ('object_id', models.IntegerField(db_index=True)),
                ('dim', models.IntegerField()),
                ('vector', models.BinaryField()),
                ('model_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'model_version'], name='api_embeddi_object__1be99f_idx'), models.Index(fields=['object_id'], name='api_embeddi_object__8a643c_idx')],
                'unique_together': {('object_type', 'object_id', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('impression', 'impression'), ('click', 'click'), ('like', 'like'), ('dismiss', 'dismiss'), ('rate', 'rate')], max_length=12)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['userId', 'action', 'created_at'], name='api_event_userId_6793af_idx'), models.Index(fields=['action', 'created_at'], name='api_event_action_4130b0_idx')],
            },
        ),
    ]
