# Generated by Django 4.2.23 on 2025-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_recommendationcache_embedding_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
